### ISSUE TITLE
No way

### ISSUE THREAD

**Issue by ddday** [PixelZerg/QuizletBot#1]
There's no way to stop it while keeping your earned score, help?

**Comment by ghost** [comment]
You're right, there is no official way to stop the bot.
For now, you can just type the command:

``` javascript
answers=null;
```

**Comment by ddday** [comment]
in the console?

**Comment by ghost** [comment]
There is now a way to stop the bot:
Type the command:

``` javascript
stopquizletbot();
```

in the console
