### ISSUE TITLE
Pls

### ISSUE THREAD

**Issue by akimball00** [PixelZerg/QuizletBot#2]
I put the code in the console, then nothing happens except thousands of errors.

**Comment by ghost** [comment]
I cannot diagnose this issue without having more information. Make sure you're actually in the _old_ space race and not the newer one called "gravity", etc...

**Comment by akimball00** [comment]
Ok, I did try to find a solution on my own. I was on the old spcae race the whole time, and it

**Comment by akimball00** [comment]
(apologies for double submission, accidentally submitted previous comment) would it would input a few answers, but then stop. However, I tried again on a set with words in Spanish and English, and it worked flawlessly. Other sets that it did not work on were all English, one had duplicate definitions, and the computer I was attempting to run the bot on was not very powerful.
