### ISSUE TITLE
SpaceRaceBot - Script not starting

### ISSUE THREAD

**Issue by iPanja** [PixelZerg/QuizletBot#3]
I can not get the Space Race Bot script to work. When I run it in console, it doesn't do anything. Sometimes it gets one or two correct, then just stops. No matter what though, it prevents me from entering any text in the text box so I am not sure what is happening. I am not receiving any errors at all though in the console.

**Comment by ghost** [comment]
Which script are you using? What is the name of the file and on which quizlet game are you running it?

**Comment by ghost** [comment]
I am completely rewriting the QuizletBot. The old code will still be available if you need it. 😄
