### ISSUE TITLE
Patched? A way to fix.

### ISSUE THREAD

**Issue by Pierce01** [PixelZerg/QuizletBot#5]
It seems to not be working, It resets every time i activate the script. I code myself, and you may be able to remake it to make the answer speed not instant, but more human like so there is less of a chance of this being detected. I'll post back here if i get the script to work, if not, hopefully you fix it, Thanks

**Comment by galacticwarrior9** [comment]
@PixelZerg

**Comment by ghost** [comment]
@Maxie01 @galacticwarrior9, Sorry for taking so long to get back to you. I just tried out the script and it is working absolutely fine for me. Can you please give me more information of the problem you are experiencing?
If you want to change the speed of the bot, change the second argument of the function in the code found here: https://github.com/PixelZerg/QuizletBot/blob/master/Source/quizletbot.js
on line 71.

``` javascript
setInterval(function()//main loop
{
    if(enabled){
        if(bno == 0){
            msctrloop();
        }else if(bno == 1){
            srloop();
        }
        if(!shownrngmsg){
        console.log("quizletbot running...");
        shownrngmsg = true;
    }

    }else{
    if(!shownmsg){console.log("quizletbot stopped!");
    shownmsg=true;
}

    }
}, 1);//<--- change this 1 here to change speed. This is delay in milliseconds
```

The bot is working for  me:
![image](https://i.snag.gy/E52SCk.jpg)

**Comment by ghost** [comment]
I am completely rewriting the QuizletBot. The old code will still be available if you need it. 😄
